spring:
  datasource:
    generate-unique-name: false
    name: coffeehouse
  thymeleaf:
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  data:
    rest:
      base-path: /data-api

logging:
  level:
    root: info
